### ISSUE TITLE
KT-1

### ISSUE THREAD

**Issue by mrisek** [unipu-ict/dnevnik-krvnog-tlaka#11]
Na screenu "Krvni tlak" se zadnja tri unosa pojavljuju u Toast poruci, a prema skici bi trebali pisati u donjem dijelu screena.

**Comment by mrisek** [comment]
Riješeno, sad se zadnja tri unosa nalaze u donjem dijelu KT screena, međutim, treba složiti još i prikaz u obliku tablice!

**Comment by akovace** [comment]
U redu, možeš uploadati to na master repository.

**Comment by ghost** [comment]
Dakle, na screenu 'Krvni tlak' preostaje nam samo još u drugom dijelu screena napraviti tablicu sa zadnjim unosima (npr. jTable)

**Comment by mrisek** [comment]
Dijana je dobila zadatak da se poigra sa prototipovima tablica koje sam objavio u test-grani :smile_cat:

**Comment by ghost** [comment]
Dakle, odlučili smo se za onu drugu tablicu? pa ako može onda tu i da postavimo :)

**Comment by mrisek** [comment]
Tako je, demokracija je presudila u korist tablice br. 2 :+1:

**Comment by ghost** [comment]
Tablica odabrana, i ubačena, zatvaram.
