### ISSUE TITLE
KT-2

### ISSUE THREAD

**Issue by mrisek** [unipu-ict/dnevnik-krvnog-tlaka#12]
Na screenu "Krvni tlak" ne bi trebala biti forma za unos, nego na screenu "Unos". Umjesto toga treba pisati zadnji korisnikov unos mjerenja krvnog tlaka.

**Comment by mrisek** [comment]
Forma za unos je maknuta i sad treba na implementirane labele postaviti vrijednosti zadnjeg izmjerenog krvnog tlaka.

**Comment by akovace** [comment]
Budem to riješio ;)

**Comment by ghost** [comment]
super riješeno! zatvaram
