### ISSUE TITLE
Ikone za KT screen

### ISSUE THREAD

**Issue by mrisek** [unipu-ict/dnevnik-krvnog-tlaka#22]
Potrebne su nam dvije ikone za screen "Krvni tlak" koje se vide na skici za projekt. Znači jedna bi bila prelazak na aktivnost UKT, a druga prelazak na "Dijagnozu" sa grafovima itd... Nije hitno, prioritet je testiranje i stabilna verzija do kraja tjedna :)

![kt](https://cloud.githubusercontent.com/assets/19214159/15583545/913357e4-2376-11e6-93b9-3578ec2455a4.jpg)

**Comment by ghost** [comment]
Da, to sam razmišljala učiniti kada odradimo cijelo testiranje i bugfixing,
jer trebam točno vidjeti koje boje će biti te ikone, pa da se sada ne zaletimo, najmanji problem je napraviti te ikone :)

**Comment by mrisek** [comment]
U potpunosti se slažem! Pametno razmišljaš :)

**Comment by ghost** [comment]
Ikone su napravljene, stoga zatvaram ovaj issue ;)
