### ISSUE TITLE
Slična aplikacija sa GitHuba

### ISSUE THREAD

**Issue by mrisek** [unipu-ict/dnevnik-krvnog-tlaka#23]
Antune, zamolit ću te da sa GitHuba skineš aplikaciju sa sljedećeg linka:
https://github.com/stevenmz/Blood-Pressure-Diary

Probaj ju pokrenuti u Android Studiju i staviti na uređaj pa mi javiš ako ima nekih sličnosti sa našom, dali se nešto da iskoristiti u svrhu poboljšanja naše aplikacije :)

Nije sad još to toliko hitno, prioritet nam je testiranje, bugfix i prva stabilna verzija do kraja tjedna :)
@djaranovic  će isto pogledati, ali više iz aspeka dizajna ;)

**Comment by akovace** [comment]
Što se tiče funkcionalnosti, aplikacija nema ništa više od naše, čak im ni graf ne radi, dizajn je basic.
Razlika je ta da mi spremamo datum, dok navedena aplikacija sprema i vrijeme unosa (h:m) koje se također sprema u varijable koje su tipa integer koje se poslje prosljeđuju u Date
`Date e = new Date(this.mYear, this.mMonth, this.mDay, this.mHour, this.mMinute);`
U samoj bazi, datum se sprema u tipu text
`this.DATABASE_CREATE = "create table " + this.TableName + " (_id integer primary key autoincrement, systolic integer, diastolic integer, heart_rate integer, entryDateTime text);";`

**Comment by mrisek** [comment]
Izvrsno istraživanje, Antune. Zadovoljan sam viđenim, pošto si ti radio našu bazu prepustit ću ti da i nama složiš istu stvar. Znači i mi želimo da nam se sprema sat i minuta svakog napravljenog unosa ;) pripremu sam ti već napravio, samo treba odkomentirati par linija :) #13 

Zatvaram Issue.
