### ISSUE TITLE
Bugfix

### ISSUE THREAD

**Issue by mrisek** [unipu-ict/dnevnik-krvnog-tlaka#4]
Kao što vidite, aplikacija je kompletirana što se tiče funkcionalnosti i radi. Međutim, sad je potrebno sprovesti idući ključni dio razvoja softvera koji se zove testiranje i bugfixing. Dijana, ti ćeš biti zadužena za testiranje aplikacije, dok ćemo Antun i ja probati popraviti greške :) to je u biti onaj zabavni dio :D

Toliko o tome za sada, čujemo se uskoro :)

**Comment by ghost** [comment]
Primljeno na znanje! ;)

**Comment by akovace** [comment]
Odlično, sviđa mi se kako napredujemo :)

**Comment by mrisek** [comment]
I ja sam zadovoljan, svi imamo pristup do Issues i možemo komentirati :)
Zatvaram Issue
