### ISSUE TITLE
UKT 10

### ISSUE THREAD

**Issue by ghost** [unipu-ict/dnevnik-krvnog-tlaka#42]
Na screenu 'Unos krvnog tlaka' desava se greska 'Nazalost, aplikacija je prestala funkcionirati', što je vjerovatno povezano sa #41 
(ta dva issuea spadaju pod validaciju)

**Comment by mrisek** [comment]
Točno. Radi se o još jednom slučaju validacije kojeg moramo pokriti. Konkretno, to je pokušaj manipuliranja praznim stringom zbpg čega dolazi do errora. Rješenje ćemo implementirati na isti način kao i kod #41 samo će se u ovom slučaju okinuti druga Toast poruka.

Srijeda - tijekom ili nakon kolegija RMA

**Comment by ghost** [comment]
Isto srijeda :+1:

**Comment by ghost** [comment]
Riješeno, pa zatvaramo ;)
