### ISSUE TITLE
Ikone aplikacije

### ISSUE THREAD

**Issue by ghost** [unipu-ict/dnevnik-krvnog-tlaka#51]
Postaviti ikone aplikacije u 4 foldera i naprviti unikatne ikone za različite vrste tlakova na screenu Povijest

**Comment by akovace** [comment]
https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html - skoro sve sam napravi, samo trebas uploadati sliku i urediti, na kraju preuzeti i staviti u folder projekta

**Comment by ghost** [comment]
to je vec napravljeno, nalazi se u folderu Dizajn, točnije u folderu ic_launcher, samo bi trebao netko to postaviti u projekt na Githubu, s obzirom da preko mog laptopa ne želi, ne može se mergati kako smo probali Matija i ja

**Comment by ghost** [comment]
Ikone postavljene danas, i napravljene unikatne ikone za različite vrste tlakova, zatvaram issue :+1:
