### ISSUE TITLE
Android dizajn

### ISSUE THREAD

**Issue by mrisek** [unipu-ict/dnevnik-krvnog-tlaka#9]
Kad budeš imala vremena baci oko na ovo please, ako procjeniš da nam može koristiti, onda ubacujemo u projekt :wink:  ako ne, možda postoji nešto slično da se može upotrijebiti u svrhu dizajna :)

https://developer.android.com/design/index.html
https://www.google.com/design/spec/style/color.html

**Comment by ghost** [comment]
Imala sam u vidu te stranice baš za današnji task tako da budem sigurno ;)

**Comment by ghost** [comment]
Upravo istraženo i zabilježeno sve što će nam koristiti prilikom dizajniranja naše aplikacije. Možemo zaključiti istraživanje i pripremu za dizajn, te krenuti na debuging i konačno provedbu dizajna ! :D

**Comment by mrisek** [comment]
Izvrsno, Dijana :)
Zatvaram Issue i vrijeme je za testiranje i bugfixing!
